config:
  target: "http://localhost:8080"
  phases:
    - duration: 60
      arrivalRate: 10
      name: "Warm up"
    - duration: 120
      arrivalRate: 20
      name: "Sustained load"
    - duration: 30
      arrivalRate: 5
      name: "Cool down"
  defaults:
    headers:
      Content-Type: "application/json"
  plugins:
    expect: {}

scenarios:
  - name: "Fetch Posts"
    flow:
      - get:
          url: "/api/v1/posts?page=1&limit=10"
          expect:
            - statusCode: 200
            - contentType: json
            - hasProperty: status
            - equals:
              - "{{ status }}"
              - "success"

  - name: "Health Check"
    weight: 10
    flow:
      - get:
          url: "/health"
          expect:
            - statusCode: 200
            - contentType: json

  - name: "Create Post and Comment Flow"
    weight: 5
    flow:
      - post:
          url: "/api/v1/auth/register"
          json:
            username: "loadtest_{{ $randomString() }}"
            email: "loadtest_{{ $randomString() }}@nimbus.com"
            password: "test123456"
          capture:
            - json: "$.data.token"
              as: "token"
            - json: "$.data.user._id"
              as: "userId"
      - think: 1
      - post:
          url: "/api/v1/posts"
          headers:
            Authorization: "Bearer {{ token }}"
          json:
            title: "Load Test Post {{ $randomString() }}"
            content: "This is a load test post created by Artillery"
      - think: 1
      - get:
          url: "/api/v1/posts?page=1&limit=5"
          headers:
            Authorization: "Bearer {{ token }}"

